version: "3"
services:
  db:
    image: mariadb:10.4
    container_name: "mariadb-10.4"
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: GO
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
  php:
    build: ./php
    container_name: "php-apache"
    volumes:
      - ./source:/var/www/html
      - ./php/vhost.conf:/etc/apache2/conf-enabled/vhost.conf
    ports:
      - "8080:80"
